//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клієнти
    {
        public int Id { get; set; }
        public string Назва { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> Код_компанії { get; set; }
        public string Надходження { get; set; }
        public Nullable<decimal> Витрати { get; set; }
    }
}
