//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Компанії
    {
        public int Код_компанії { get; set; }
        public string C_Назва_компанії { get; set; }
    }
}
